# Name of the Fly app (must be unique across fly.io)
app = "carpet-invoices"

# Primary region for deployment
primary_region = "syd"

[build]

[env]
  # Set Flask environment and port for the app to bind to
  FLASK_ENV = "production"
  PORT      = "5000"

[[mounts]]
  # Attach a named volume to persist data at /app/data
  source      = "carpet_invoices_data"
  destination = "/app/data"

[deploy]
  # Command to run database migrations or initial setup on release
  release_command = "python -c 'from main import app, db; app.app_context().push(); db.create_all()'"

[[services]]
  # Internal port the service listens on (must match PORT env var)
  internal_port = 5000
  protocol      = "tcp"
  # Processes to run; must match a command in your Dockerfile or app code
  processes     = ["app"]

  [services.concurrency]
    # Connection limits to protect against overload
    type       = "connections"
    soft_limit = 20
    hard_limit = 25

  [[services.ports]]
    # Public HTTP port; force HTTPS redirects
    port        = 80
    handlers    = ["http"]
    force_https = true

  [[services.ports]]
    # Public HTTPS port with TLS termination
    port      = 443
    handlers  = ["tls", "http"]