# fly.toml app configuration file generated for carpetinvoicemanager on 2025-07-11T11:40:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'carpetinvoicemanager'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
