# fly.toml app configuration file generated for carpet-invoices
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "carpet-invoices"
primary_region = "syd"  # Sydney region for New Zealand users

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "carpet_invoices_data"
  destination = "/app/data"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"

# Secrets that need to be set:
fly secrets set SESSION_SECRET=$(openssl rand -base64 32)
fly secrets set ADMIN_USERNAME=admin
fly secrets set ADMIN_PASSWORD=greenlight24
fly secrets set DATABASE_URL=sqlite:////app/data/carpet_invoices.db

[deploy]
  release_command = "python -c 'from app import app, db; app.app_context().push(); db.create_all()'"

[processes]
  app = "python main.py"

[[services]]
  http_checks = []
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

# Volume for persistent data storage
[volumes]
  carpet_invoices_data = "1gb"
